apiVersion: v1
kind: Template
labels:
  template: fedora-okd-builder
metadata:
  name: fedora-okd-builder
  openshift.io/display-name: Fedora OKD Builder Environment
  iconClass: icon-go-gopher
  template.openshift.io/long-description: |-
    The Fedora OKD builder container provides an environment
    in which developers can work with the Origin source code without needing
    to install any tools other than a container runtime on their system.
parameters:
- name: SOURCE_REF
  displayName: Source Ref
  description: Git reference to use for building the OKD builder environment image
  value: master
  required: false
- name: SOURCE_URL
  displayName: Source URL
  description: Git source URL to use for building the OKD builder environment image
  value: https://github.com/openshift/release.git
  required: false
- name: PUSH_REPOSITORY
  value: docker.io/openshift/fedora-okd-builder
  required: false
- name: BASE_REPOSITORY
  value: fedora:30
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: fedora-okd-builder
    name: fedora-okd-builder
  spec:
    tags:
    - name: base
      from:
        kind: DockerImage
        name: ${BASE_REPOSITORY}
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: fedora-okd-builder
    name: "fedora-okd-builder-golang-1.12"
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: DockerImage
        name: "${PUSH_REPOSITORY}:golang-1.12"
      pushSecret:
        name: "dockerhub"
    source:
      git:
        ref: "${SOURCE_REF}"
        uri: "${SOURCE_URL}"
      contextDir: "projects/fedora-okd-builder/golang-1.12/"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: origin-release:base
        imageOptimizationPolicy: SkipLayers
    triggers:
    - imageChange: {}
      type: ImageChange