---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: multi-arch-ci-tools
spec:
  tags:
  - name: pod-scaler
    from:
      kind: DockerImage
      name: 'quay.io/multi-arch/ci-tools:pod-scaler'
